backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'project' # Used in routes, e.g., /admin/collections/blog
    label: 'Project' # Used in the UI
    folder: 'content/projects' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          format: 'Do MMM YYYY',
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Category Tags',
          name: 'tags',
          widget: 'list',
          required: false
        }
      - {
          label: 'Description',
          name: 'descriptionTexts',
          widget: 'list',
          field: { label: Description Text, name: descriptionText, widget: 'markdown' }
        }

  - name: 'about'
    label: 'About'
    folder: 'content/about'
    create: true
    slug: '{{slug}}'
    format: 'json'
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string'}
      - {
          label: 'Profile Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Industries', name: 'industries', widget: 'markdown'}
      - { label: 'Experience', name: 'experience', widget: 'markdown'}
      - { label: 'Hobbies', name: 'hobbies', widget: 'markdown'}
      - { label: 'Social', name: 'social', widget: 'markdown'}
